
spring:
#  flyway:
#    enabled: true
#    baseline-on-migrate: true
#    locations: classpath:db/migration
#    default-schema: public
  datasource:
    url: jdbc:postgresql://localhost:5432/cloudconnect
    username: clouduser
    password: cloudpassword
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # Explicitly set the dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: 8081

security:
  jwt:
    secret: mySecretKey
    expiration: 3600000
    refresh-token-expiration: 604800000
